// reports
export const REPORT_LIST = 'REPORT_LIST';
export const SET_REPORT_DATA = 'SET_REPORT_DATA';
export const GET_REPORT_DETAIL = 'GET_REPORT_DETAIL';

export const LOGIN = 'LOGIN';
export const LOG_OUT = 'LOG_OUT';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const SEND_PASSWORD_RESET_LINK = 'SEND_PASSWORD_RESET_LINK';

export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA';
export const GET_GROWTH_RATE = 'GET_GROWTH_RATE';
export const GET_TREND = 'GET_TREND';
export const GET_CONTRACT_EXPRIES = 'GET_CONTRACT_EXPRIES';
export const GET_TOTAL_WASTE_DATA = 'GET_TOTAL_WASTE_DATA';
export const GET_TOTAL_WASTE_BY_ORGANIZATION = 'GET_TOTAL_WASTE_BY_ORGANIZATION';
export const GET_TOTAL_PICKUPS_BY_ORGANIZATION = 'GET_TOTAL_PICKUPS_BY_ORGANIZATION';
export const GET_CONTRACT_DURATION_FOR_EACH_ORGANIZATION = 'GET_CONTRACT_DURATION_FOR_EACH_ORGANIZATION';
export const GET_MONTHLY_WASTE_DATA = 'GET_MONTHLY_WASTE_DATA';
export const GET_TRENDLINE_WASTE_DATA = 'GET_TRENDLINE_WASTE_DATA';
export const CHANGE_FILTER_ORGANIZATION = 'CHANGE_FILTER_ORGANIZATION';

export const GET_ORGANIZATION_LIST = 'GET_ORGANIZATION_LIST';
export const GET_ORGANIZATION_DETAIL = 'GET_ORGANIZATION_DETAIL';
export const ADD_NEW_ORGANIZATION = 'ADD_NEW_ORGANIZATION';
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';
export const DELETE_ORGANIZATION = 'DELETE_ORGANIZATION';

export const GET_USER_LIST = 'GET_USER_LIST';
export const GET_USER_DETAIL = 'GET_USER_DETAIL';
export const GET_DRIVER_LIST = 'GET_DRIVER_LIST';
export const GET_OPERATION_TEAM_LIST = 'GET_OPERATION_TEAM_LIST';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const DELETE_USER = 'DELETE_USER';

export const GET_LOGISTICS_SCHEDULE_LIST = 'GET_LOGISTICS_SCHEDULE_LIST';
export const GET_TODAY_LOGISTICS_SCHEDULE = 'GET_TODAY_LOGISTICS_SCHEDULE';
export const ADD_NEW_LOGISTICS = 'ADD_NEW_LOGISTICS';
export const GET_LOGISTICS_SCHEDULE_DETAIL = 'GET_LOGISTICS_SCHEDULE_DETAIL';
export const UPDATE_LOGISTICS = 'UPDATE_LOGISTICS';
export const GET_WAY_DETAIL = 'GET_WAY_DETAIL';

export const CHANGE_PICKUP_TIME = 'CHANGE_PICKUP_TIME'; // Schedule Pickup Time
export const CHANGE_START_DATE = 'CHANGE_START_DATE'; // Organization Join Date
export const CHANGE_EXPIRED_DATE = 'CHANGE_EXPIRED_DATE';
export const CHANGE_LOCATION = 'CHANGE_LOCATION';

export const GET_TRAINING_LIST = 'GET_TRAINING_LIST';
export const GET_TRAINING_DETAIL = 'GET_TRAINING_DETAIL';
export const CHANGE_TRAINING_DATE = 'CHANGE_TRAINING_DATE';
export const UPDATE_TRAINING = 'UPDATE_TRAINING';

export const GET_BINS_LIST = 'GET_BINS_LIST';
export const GET_BIN_DETAIL = 'GET_BIN_DETAIL';
export const ADD_NEW_BIN = 'ADD_NEW_BIN';
export const UPDATE_BIN = 'UPDATE_BIN';
export const DELETE_BIN = 'DELETE_BIN';


export const GET_BIN_ORDER_LIST = 'GET_BIN_ORDER_LIST';
export const GET_BIN_ORDER_DETAIL = 'GET_BIN_ORDER_DETAIL';
export const ADD_NEW_BIN_ORDER = 'ADD_NEW_BIN_ORDER';
export const UPDATE_BIN_ORDER = 'UPDATE_BIN_ORDER';
export const DELETE_BIN_ORDER = 'DELETE_BIN_ORDER';

export const GET_PAYMENT_LIST = 'GET_PAYMENT_LIST';
export const GET_PAYMENT_DETAIL = 'GET_PAYMENT_DETAIL';

export const GET_QUIZ_LIST = 'GET_QUIZ_LIST';
export const GET_QUIZ_DETAIL = 'GET_QUIZ_DETAIL';

export const ADD_NEW_USER_ANS_QUIZ = 'ADD_NEW_USER_ANS_QUIZ';
export const DELETE_USER_ANS_QUIZ = 'DELETE_USER_ANS_QUIZ';

export const GET_TRAINING_SLIDE_LIST = 'GET_TRAINING_SLIDE_LIST';
export const GET_TRAINING_SLIDE_DETAIL = 'GET_TRAINING_SLIDE_DETAIL';

export const ADD_NEW_ORDER = 'ADD_NEW_ORDER';
