name: Deploy to Render

on:
  push:
    branches:
      - develop

jobs:
  render-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d1d5b295pdvs73acvo0g?key=QcfJvnKM2mU"
